### ISSUE TITLE
Building a fetch relative to a base directory or URL

### ISSUE THREAD

**Issue by brettz9** [bergos/file-fetch#12]
Hi,

Am a bit tied up at the moment to submit a PR (and have a kludgy working solution that works for me for now), but would be really nice if `file-fetch` could end up supporting building a `fetch` which could be relative to a specific directory, e.g., the current file's directory--making for more readable file paths. Was wondering your thoughts about that.

Since it'd be great to have an ESM export too, it'd be nice if the base path could be derived from a (file) URL as well, so all that would be needed would be to pass in `import.meta.url` (no less important since `__dirname` and `__filename` are [not supported in Node ESM](https://nodejs.org/api/esm.html#esm_no_require_exports_module_exports_filename_dirname)).

I was envisioning something like:

```js
import {buildFetch} from 'file-fetch';
const fetch = buildFetch({
    baseURL: import.meta.url
});
```

or in CJS:

```js
const {buildFetch} = require('file-fetch');
const fetch = buildFetch({
    basePath: __dirname
});
```

The default (if no `baseURL` or `basePath` were found), could just be `process.cwd` (as I recall `file-fetch` works now, though in such a case, one wouldn't need `buildFetch`).

**Comment by bergos** [comment]
@brettz9 Sorry for the late reply. I just noticed that I wrote the message but didn't press "Comment" when I looked into this browser tab.

That would be a great feature. What do you think about naming the function `create` or `factory`? Even with destructuring assignment, in my head, I still read it like `file-fetch.(create|factory)`, so we could skip one `fetch`. Not sure why, but somehow I prefer `create` or `factory` over `build`. Maybe `build` reminds me too much about the Java interface with names close to the line character limit ;-)

I have many packages with support for older Node.js versions which don't support ESM. Since this package can't be run in the browser and the benefit would be not that high, I would postpone that topic to a later point where we have more Node.js versions with ESM support. Not sure if it makes sense, but we could tackle already the `__dirname` problem to reduce the changes for ESM in the future.

**Comment by brettz9** [comment]
`create` sounds best to my tastes (though `factory` would be fine also). I hear you about avoiding the Java-like names!

Re: dropping `fetch`, just to consider if you hadn't that if importing into a large code base, `create` could be less appealing as a default for some in being more ambiguous and potentially clashable with other local variables (and though one could import as `import * as fileFetch` and then use `fileFetch.create`, this is less than ideal as [tree-shaking](https://rollupjs.org/guide/en/#tree-shaking) would not occur and the format may therefore be discouraged by [linting rules](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-namespace.md) as well).

It is, however, at least possible for one to rename within the import like `import {create as createFetch} ...` if you still prefer that approach, but just offering the thought to make it more natural to import more safely (re: clashes) by default.

**Comment by bergos** [comment]
I'm aware of the problem and I would use `as` to map it to my local name. Maybe in the same repo I would use a short unique name, but in a package, a short, but hopefully unique name could still lead to clashes. E.g. having that feature in a http fetch client would be also nice and the export could be also called `createFetch`. The other option would adding the package name to all exports. The name get's ugly and people may map the name. That's why I rather keep it short and let the users decide how they want to name it.
